summary: A command-line tool to help you insert the correct compiler options when compiling objects and/or linking libraries
webpage: https://freedesktop.org/wiki/Software/pkg-config
version: 0.29.2
bin-url: https://github.com/leleliu008/uppm-package-repository-linux-x86_64/releases/download/2025.03.18/pkg-config-0.29.2-linux-x86_64.release.tar.xz
bin-sha: b11d5a9143b7f051ebf6e71dfa61e606aee4766951dfb530f2612daf79fbefd3
